name: Super Lig Tum Kadrolar
on:
  schedule:
    - cron: '0 0 2 * *'
  workflow_dispatch:

jobs:
  update-superlig:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Süper Lig Takımlarını Çek ve Birleştir
        run: |
          mkdir -p temp_squads
          SEASON=2024
          
          echo "Sabit Sezon: $SEASON yılı Süper Lig takımları çekiliyor..."
          
          # Takım listesini al
          curl -s -X GET "https://v3.football.api-sports.io/teams?league=203&season=$SEASON" -H "x-apisports-key: ${{ secrets.API_KEY }}" -o takimlar.json
          TEAM_IDS=$(jq '.response[].team.id' takimlar.json)
          
          # Her takımın kadrosunu temp klasörüne çek
          for ID in $TEAM_IDS; do
            # Konyaspor'un ID'si 607 ise isteği atla
            if [ "$ID" == "607" ]; then
              echo "Konyaspor (ID: 607) atlanıyor..."
              continue
            fi
            
            echo "Takım $ID kadrosu çekiliyor..."
            curl -s -X GET "https://v3.football.api-sports.io/players/squads?team=$ID" -H "x-apisports-key: ${{ secrets.API_KEY }}" -o "temp_squads/$ID.json"
            sleep 7 
          done
          
          echo "Bütün dosyalar tek bir JSON'da birleştiriliyor..."
          # Bütün takımları nizami tek bir array (dizi) içinde birleştir ve ana dizine kaydet
          jq -s '{ response: [ .[].response[0] | select(. != null) ] }' temp_squads/*.json > superlig_squads.json
          
          # Çöp (geçici) dosyaları sil
          rm -rf temp_squads takimlar.json
          
      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name "SuperLig Botu"
          git config --global user.email "actions@github.com"
          git add superlig_squads.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Süper Lig Tek Dosya Olarak Guncellendi" && git push)
